# Before Script
before_script:
  - composer self-update
  - composer install --prefer-dist > /dev/null
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate:refresh

# Services
services:
  - mysql:latest

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead

# PHP 5.5
php:5.5:
  image: bobey/docker-gitlab-ci-runner-php5.5
  script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --colors --debug  --coverage-text

# PHP 5.6
php:5.6:
  image: bobey/docker-gitlab-ci-runner-php5.6
  script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --colors --debug  --coverage-text